apiVersion: batch/v1
kind: CronJob
metadata:
  name: algo-trading-app
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 600
      template:
        metadata:
          labels:
            app: algo-trading-app
        spec:
          containers:
            - name: algo-trading-app
              image: your-docker-image:latest
              env:
                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: stock-data-api-key
                      key: api-key
              resources:
                requests:
                  memory: "512Mi"
                  cpu: "500m"
                limits:
                  memory: "1Gi"
                  cpu: "1"
          restartPolicy: OnFailure
