apiVersion: batch/v1
kind: CronJob
metadata:
  name: algo-trading-app
spec:
  schedule: "*/15 * * * *"  # Runs every 15 minutes
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: algo-trading-app
        spec:
          containers:
            - name: algo-trading-app
              image: your-docker-image:latest  # Replace with your Docker image
              env:
                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: stock-data-api-key
                      key: api-key
                # Add other environment variables or configurations as needed
          restartPolicy: OnFailure
