apiVersion: apps/v1
kind: Deployment
metadata:
  name: algo-trading-bot
  labels:
    app: algo-trading-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: algo-trading-bot
  template:
    metadata:
      labels:
        app: algo-trading-bot
    spec:
      containers:
        - name: algo-trading-bot
          image: algo-trading-bot:1.0.0
          # Logs are collected by kubernetes and analyzed. No need to expose any ports.

