apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: algo-trading-bot-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: algo-trading-bot
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
