apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bot-service-monitor
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: algo-trading-bot
  endpoints:
    - port: metrics
      interval: 30s
